<?php
/**
 * @file
 * Code for the F1 GDPR module.
 */

/**
 * Implements hook_page_alter().
 *
 * Adds JavaScript to the <head> to disable Google Analytics tracking if the
 * user has not given consent. Assumes the site is using the google_analytics
 * module to add GA to the site.
 */
function f1_gdpr_page_alter(&$page) {
  $ga = variable_get('googleanalytics_account', '');

  $script = <<<EOS
    var match = document.cookie.match(new RegExp('has_consent=([^;]+)'));
    const has_consent = match ? parseInt(match[1]) : -1;
    if('{$ga}' && has_consent < 1) {
      window['ga-disable-{$ga}'] = true;
    }
EOS;

  if($ga) {
    drupal_add_js($script, array('scope' => 'header', 'group' => -1000,
      'type' => 'inline', 'requires_jquery' => FALSE));
  }

  drupal_add_css(drupal_get_path('module', 'f1_gdpr') . '/css/f1_gdpr.css');
}

/**
 * Function to embed toggle buttons for the has_consent cookie, e.g. on a
 * Cookie Policy page.
 */
function f1_gdpr_embed_toggle_buttons() {
  include drupal_get_path('module', 'f1_gdpr') . '/includes/toggle_buttons.html';
}
